/*
 * Copyright 2015 - 2015 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.notenik;

  import com.powersurgepub.psutils.*;
  import java.io.*;
  import java.net.*;

/**
 Display info about a file. 

 @author Herb Bowie
 */
public class FileInfoWindow 
    extends javax.swing.JFrame 
        implements WindowToManage {

  /**
   Creates new form FileInfoWindow
   */
  public FileInfoWindow() {
    initComponents();
  }
  
  public void setFile(String fileStr) {

    FileName fileName = new FileName(fileStr);
    folderText.setText(fileName.getPath());
    File folder = new File (fileName.getPath());
    boolean folderExists = folder.exists();
    if (folderExists) {
      folderExistsLabel.setText("Folder exists.");
    } else {
      folderExistsLabel.setText("Folder does not exist.");
    }
    fileText.setText(fileName.getFileName());
    fileExistsLabel.setText("File does not exist");
    if (folderExists) {
      File file = fileName.getFile();
      if (file.exists()) {
        fileExistsLabel.setText("File exists.");
      }
    }
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    folderLabel = new javax.swing.JLabel();
    folderText = new javax.swing.JLabel();
    folderExistsLabel = new javax.swing.JLabel();
    fileLabel = new javax.swing.JLabel();
    fileText = new javax.swing.JLabel();
    fileExistsLabel = new javax.swing.JLabel();

    setTitle("File Info");
    setMinimumSize(new java.awt.Dimension(720, 240));
    getContentPane().setLayout(new java.awt.GridBagLayout());

    folderLabel.setText("Folder:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(folderLabel, gridBagConstraints);

    folderText.setText("  ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(folderText, gridBagConstraints);

    folderExistsLabel.setText("Folder exists. ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(folderExistsLabel, gridBagConstraints);

    fileLabel.setText("File:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(fileLabel, gridBagConstraints);

    fileText.setText("  ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(fileText, gridBagConstraints);

    fileExistsLabel.setText("File exists.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(fileExistsLabel, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel fileExistsLabel;
  private javax.swing.JLabel fileLabel;
  private javax.swing.JLabel fileText;
  private javax.swing.JLabel folderExistsLabel;
  private javax.swing.JLabel folderLabel;
  private javax.swing.JLabel folderText;
  // End of variables declaration//GEN-END:variables
}
